# (PART) Getting Started {-}

# Introduction to Packaging {#intro}

Often, small snippets of code grow in usefulness and importance, which creates a need to share and distribute their contents. `r fontawesome::fa("r-project")` and `r fontawesome::fa("python")` libraries require _packaging_, otherwise distributing code becomes problematic and brittle. A package bundles together code, data, documentation, and tests, and is easy to share with others.

```{block, type='note'}
People often use the terms "library" and "package" synonymously. Although there are some semantical differences between R and Python, here is how you can think of the two terms:

- __library__: generally refers to source code that has been installed on an operating system in a centralized location and can be imported into a current session. When you use `pip list` (Python) or `installed.packages()` (R) you will see a list of _installed_ packages, which we refer to as libraries. When you `import pkg` (Python) or `library(pkg)` (R) you are loading the `pkg` library into your current session for use.

- __package__: generally refers to source code that is bundled up in a way that a package manager can host. [PyPI](https://pypi.org/) and [CRAN](https://cran.r-project.org/) are the two primary public package managers for Python and R. When you `pip install pkg` (Python) or `install.packages("pkg")` (R) you are installing the `pkg` package from a package manager onto a computer.
```

## Why is packaging important

 Why write a package? 
 
- __To share with others__: Bundling your code into a package makes it easy for other people to use it, because like you, they already know how to use packages. If your code is in a package, any `r fontawesome::fa("r-project")` or `r fontawesome::fa("python")` user can easily download it, install it and learn how to use it.
- __To make processes reproducible__: When certain code processes are repeated, rather than copy-n-pasting (error prone!) packaging helps to ensure the same procedures are executed in the same way. This leads to standardized tools for standardized conventions and can save you and others time.
- __To track changes__: Packaging helps to formulize version changes of a project. Versioning allows developers a way to communicate the type of changes made to a project (i.e. bug fixes versus feature enhancement). It also allows users to "pin" a specific version that works for their project. For example, although a current package may have a version 3.2.1, your project depends on specific functionality provided in version 2.9.7. Pinning allows you to request and use that specific version.
- __To communicate with users__: Beyond versioning, packaging helps with communication between developers and end-users. Detailed documentation helps the end-users implement the code, a change log can communcate the progression of a package over its versions, users can communicate to the developers regarding bugs they've found or suggested feature enhancements.
- __To provide reliability__: Packaging helps to modularize code in a way that allows for, and simplifies, testing procedures. This means as your source code grows, or as you get feedback from end-users, so should your test suite grow to help improve reliability of the code base. This results in code that is reliable and trustworthy.
- __To deploy production work__: You may have code that is never reused by others; however, the code is put into production to formalize the processesing and output of the code. Packaging your project is a great way to organize, maintain, and distribute your work into production.

## When packaging might not be needed

To be clear, it is not necessary to package your code to address all the bullets in the previous section; but it will definitely make them easier to achieve. However, there are times when writing a package is not necessary. For example:

- __Exploratory analysis__: The exploratory phase of a project is very interactive and contains many unknowns. You may find yourself repeating some code, which may be a good time to write and reuse small functions. However, this is not the phase to start writing a package. It's best to wait and see what results from your exploratory analysis. If there are steps in the process (i.e. data prep, model execution) that you later determine are common steps that will often be repeated in the future then a package may result from post-exploration project review.
- __One-off projects__: Many times we perform one-off ad-hoc projects. Sometimes we may be able to abstract some steps in these projects that may be repeated but often these projects contain very unique steps that are not often repeated. You most likely will use packages in your analysis but writing a package based on a one-off project is rarely a good use of time.
- __Small scripts__: Sometimes a simple `r fontawesome::fa("r-project")`, `r fontawesome::fa("python")`, or Bash script can go a long way and serve your primary purpose. Small individual scripts can be easy to build, execute and orchestrate; however, if you notice this small script starting to grow in size and use then it's time to start thinking of converting it to a package.

```{block, type='note'}
Although the above type of work may not justify a package, it often still justifies good software engineering practices such as modularity and unit tests!
```

## An opinionated approach

It is important to understand that there are several approaches and strategies to writing packages. Even within a single language there are different ways to structure a package. Consequently, understand that this book demonstrates the best practices we have found for developing, maintaining, and distributing packages. Our goal is to provide you with a short runway to writing packages as quickly as possible while following commonly used best practices. 

```{block, type='note'}
This is a lot to learn, but don’t feel overwhelmed. Start with a minimal subset of useful features and build up over time.
```

As you write more packages you will begin to learn the lower-level details and alternative options. Do not shy away from these details as we highly recommend that you learn them. In fact, below are some additional resources that will take you to the official R and Python packaging documentation. Realize that the details in these documents can make them challenging to read. That is ok and to be expected. Our suggestion is to get the basics down, which we cover in this book, and slowly expand your knowledge base by writing more packages.

- `r fontawesome::fa("r-project")`: [Creating R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html#Creating-R-packages)
- `r fontawesome::fa("python")`: [Python Packaging User Guide](https://packaging.python.org/)
