# Package Structure {#structure}

Packages have a specific structure required to be bundable, deployable, and usable. There are a set of minimum files required for both `r fontawesome::fa("r-project")` and `r fontawesome::fa("python")` packages but you will often see additional files in packages. Though how these files are actually named will differ between `r fontawesome::fa("r-project")` and `r fontawesome::fa("python")`, the organization follows a very similar pattern. The primary files and directories you will be concerned about include:

* __Package metadata__: Every package requires important metadata about the package. This file will declare various information such as package name, description, dependencies, author(s), contact information and more. Chapter \@ref(metadata) will discuss the details of this file.
* __Source code directory__: This is the directory that contains all the source code for end-user functionality. Here you will organize your classes, functions, etc. into one or more .R / .py scripts. Chapter \@ref(code) will discuss requirements, approaches and best practices for organizing this directory.
* __Test directory__: Every package should always contain a testing framework. These tests should include a minimum of unit tests but can also contain integration or environment specific tests. Chapter \@ref(test) will discuss the most common test approaches for `r fontawesome::fa("r-project")` and `r fontawesome::fa("python")`.
* __Documentation directory__: Although not necessary, good packages often will have detailed documentation hosted as a static website. These files are generally kept in a `/docs` folder. Chapter \@ref(website) will discuss how to make beautiful websites for your package.
* __License file__: Specifies who can and cannot use your package. This file is related to specifications made in the metadata file and will be discussed in Chapter \@ref(metadata).
* __Changelog__: A changelog is a log or record of all notable changes made to a project. We will discuss the changelog in Chapter \@ref(changelog).
* __README__: The README is often one of the first files a user sees when going to the source code location (typically Github). A good README will provide useful instructions to get started using the package quickly and also where to go to find more detailed information. We will discuss what a good README looks like in Chapter \@ref(readme).
* __Other various config or requirement files__: You will often see additional files in packages. These may be various configuration files or other package components. Many of these you will be introduced along the way through this book and others will be explicitly discussed in Chapter \@ref(other).

This general structure will look like the following and the sections that follow will illustrate and describe the exact structure setup for each language.

```sh
.
├── package metadata file
├── source code directory
│   ├── script 1
│   ├── script 2
│   └── script n
├── test directory
│   ├── script 1
│   ├── script 2
│   └── script n
├── documentation directory
│   └── various doc files
├── license file
├── changelog file
├── README
└── other various config files and components
```

For the sections that follow let's assume we are creating a package called __mypkg__.

## `r fontawesome::fa("r-project")`

Within R, the basic structure of your package will look like the following. The unique items here are:

- __DESCRIPTION__: This is the file that contains the primary package metadata.
- __R/__: The R directory is where all the source code resides.
- __NEWS__: It is common convention in many R packages to title the changelog as "NEWS".

```sh
mypkg
├── DESCRIPTION
├── R
├── tests
├── docs
├── LICENSE
├── NEWS
└── README
```

The rest of the files are consistent with the previous section. As you'll see in the next chapter, additional files will be produced when we build the package but these are the primary directories and files to get going with an R package.

## `r fontawesome::fa("python")`

Within Python, the basic structure of your package will look like the following. The unique items here are:

- __setup.py__: This is the file that contains the primary package metadata.
- __src/__: The src directory is where all the source code resides.

```sh
mypkg
├── setup.py
├── src
├── tests
├── docs
├── LICENSE
├── CHANGELOG
└── README
```

The rest of the files are consistent with the first section. As you'll see in the next chapter, additional files often included to help configure the developer environment for a package but these are the primary directories and files to create a baseline Python package.
